// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package sessionservice

import (
	"context"
	"time"

	"google.golang.org/adk/session"
)

// Service is a session storage service.
//
// It provides a set of methods for managing sessions and events.
type Service interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Delete(context.Context, *DeleteRequest) error
	// AppendEvent is used to append an event to a session.
	AppendEvent(context.Context, StoredSession, *session.Event) error
}

// Mem returns an in-memory implementation of the session service.
func Mem() Service {
	return &inMemoryService{}
}

// StoredSession represents a session.
//
// Events and state can be modified only via the Service methods.
type StoredSession interface {
	// ID uniquely identifies the session.
	ID() session.ID
	// State returns the session state.
	State() session.ReadOnlyState
	// Events returns the list of events in the session.
	Events() session.Events
	// Updated returns the last updated time of the session.
	Updated() time.Time
}

// CreateRequest represents a request to create a session.
type CreateRequest struct {
	AppName string
	UserID  string
	// SessionID is the client-provided ID of the session to create.
	// Optional: if not set, it will be autogenerated.
	SessionID string
	// State is the initial state of the session.
	State map[string]any
}

// CreateResponse represents a response for newly created session.
type CreateResponse struct {
	Session StoredSession
}

// GetRequest represents a request to get a session.
type GetRequest struct {
	ID session.ID

	// NumRecentEvents returns at most NumRecentEvents most recent events.
	// Optional: if zero, the filter is not applied.
	NumRecentEvents int
	// After returns events with timestamp >= the given time.
	// Optional: if zero, the filter is not applied.
	After time.Time
}

// GetResponse represents a response from Get.
type GetResponse struct {
	Session StoredSession
}

// ListRequest represents a request to list sessions.
type ListRequest struct {
	AppName string
	UserID  string
}

// ListResponse represents a response from List.
type ListResponse struct {
	Sessions []StoredSession
}

// DeleteRequest represents a request to delete a session.
type DeleteRequest struct {
	ID session.ID
}

// TODO: potentially consider returning lightweight struct in the List().
// type SessionInfo struct {
// 	ID      session.ID
// 	Updated time.Time
// }
