// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package database

import (
	"strings"
	"testing"
	"time"

	"github.com/glebarez/sqlite"
	"gorm.io/gorm"

	"google.golang.org/adk/platform"
	"google.golang.org/adk/session"
	"google.golang.org/adk/session/sessiontestsuite"
)

func Test_databaseService(t *testing.T) {
	opts := sessiontestsuite.SuiteOptions{SupportsUserProvidedSessionID: true}
	sessiontestsuite.RunServiceTests(t, opts, func(t *testing.T) session.Service {
		return emptyService(t)
	})
}

func Test_databaseService_CreateUsesProviders(t *testing.T) {
	fixedTime := time.Date(2024, time.January, 2, 3, 4, 5, 0, time.UTC)
	ctx := platform.WithTimeProvider(t.Context(), func() time.Time { return fixedTime })
	ctx = platform.WithUUIDProvider(ctx, func() string { return "fixed-session-id" })

	s := emptyService(t)
	resp, err := s.Create(ctx, &session.CreateRequest{AppName: "app", UserID: "user"})
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	if got := resp.Session.ID(); got != "fixed-session-id" {
		t.Errorf("autogenerated session ID = %q, want provider value %q", got, "fixed-session-id")
	}
	if got := resp.Session.LastUpdateTime(); !got.Equal(fixedTime) {
		t.Errorf("LastUpdateTime() = %v, want provider value %v", got, fixedTime)
	}
}

func emptyService(t *testing.T) *databaseService {
	t.Helper()
	gormConfig := &gorm.Config{
		PrepareStmt: true,
	}

	service, err := NewSessionService(sqlite.Open("file::memory:?cache=shared"), gormConfig)
	if err != nil {
		t.Fatalf("Failed to create session service: %v", err)
	}
	dbservice, ok := service.(*databaseService)
	if !ok {
		t.Fatalf("invalid session service type")
	}

	err = AutoMigrate(service)
	if err != nil {
		t.Fatalf("Failed to AutoMigrate db: %v", err)
	}

	t.Cleanup(func() {
		t.Log("CLEANUP: Deleting all rows from tables...")

		// Define models in Child-to-Parent order
		modelsToDelete := []any{
			&storageEvent{}, // Child-most
			&storageSession{},
			&storageUserState{},
			&storageAppState{}, // Parent-most
		}

		for _, model := range modelsToDelete {
			// GORM statement parser to get table names
			stmt := &gorm.Statement{DB: dbservice.db}
			// Parse the model to get its table name
			if err := stmt.Parse(model); err != nil {
				t.Errorf("Failed to parse model schema for cleanup: %v", err)
				continue
			}
			tableName := stmt.Table

			// Exec with "WHERE true" instead of gorm.Delete()
			// satisfies Spanner's requirement for a WHERE clause.
			if err := dbservice.db.Exec(`DELETE FROM ` + tableName + ` WHERE true`).Error; err != nil {
				t.Errorf("Failed to delete from table %s: %v", tableName, err)
			}
		}
		sqlDB, err := dbservice.db.DB()
		if err != nil {
			t.Errorf("Failed to get underlying *sql.DB: %v", err)
			return
		}
		if err := sqlDB.Close(); err != nil {
			t.Errorf("Failed to close database connection: %v", err)
		}
	})

	return dbservice
}

func TestDatabaseService_AppendEvent_PreservesInputEventTempState(t *testing.T) {
	ctx := t.Context()
	s := emptyService(t)

	createResp, err := s.Create(ctx, &session.CreateRequest{
		AppName: "testapp",
		UserID:  "testuser",
	})
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}

	event := &session.Event{
		ID:        "event1",
		Timestamp: time.Now(),
		Actions: session.EventActions{
			StateDelta: map[string]any{
				"temp:k1": "v1",
				"sk":      "v2",
			},
		},
	}

	if err := s.AppendEvent(ctx, createResp.Session, event); err != nil {
		t.Fatalf("AppendEvent failed: %v", err)
	}

	// Verify that the input event pointer's StateDelta map was not mutated in place.
	if _, exists := event.Actions.StateDelta["temp:k1"]; !exists {
		t.Errorf("expected temp:k1 to be preserved on input event after AppendEvent, but it was removed: %v", event.Actions.StateDelta)
	}
	if event.Actions.StateDelta["sk"] != "v2" {
		t.Errorf("expected non-temp key sk to remain in input event, got: %v", event.Actions.StateDelta)
	}

	// Verify that the stored event in the session has temp keys stripped.
	var storedEvent *session.Event
	for ev := range createResp.Session.Events().All() {
		storedEvent = ev
	}
	if storedEvent == nil {
		t.Fatalf("expected stored event in session, got nil")
	}
	if _, exists := storedEvent.Actions.StateDelta["temp:k1"]; exists {
		t.Errorf("expected temp:k1 to be stripped from stored event, but it still exists: %v", storedEvent.Actions.StateDelta)
	}
	if storedEvent.Actions.StateDelta["sk"] != "v2" {
		t.Errorf("expected non-temp key sk on stored event, got: %v", storedEvent.Actions.StateDelta)
	}
}

// TestDatabaseService_AppendEvent_StaleErrorFormatsTimestamps guards that the
// stale-session error renders human-readable wall-clock timestamps rather than
// ~1970 dates. The values compared are UnixMicro() microseconds, so formatting
// them via time.Unix(0, x) (whose second arg is nanoseconds) is off by 1000x
// and collapses every real timestamp to 1970-01-2x. See issue #1170.
func TestDatabaseService_AppendEvent_StaleErrorFormatsTimestamps(t *testing.T) {
	s := emptyService(t)
	t0 := time.Date(2026, time.July, 17, 10, 0, 0, 0, time.UTC)
	createCtx := platform.WithTimeProvider(t.Context(), func() time.Time { return t0 })
	created, err := s.Create(createCtx, &session.CreateRequest{AppName: "app", UserID: "user"})
	if err != nil {
		t.Fatalf("Create: %v", err)
	}
	// A second, independent handle on the same session — still pinned at t0.
	got, err := s.Get(t.Context(), &session.GetRequest{AppName: "app", UserID: "user", SessionID: created.Session.ID()})
	if err != nil {
		t.Fatalf("Get: %v", err)
	}
	staleHandle := got.Session
	// Advance the stored session past t0 by appending through the fresh handle.
	t1 := time.Date(2026, time.July, 17, 11, 0, 0, 0, time.UTC)
	if err := s.AppendEvent(t.Context(), created.Session, &session.Event{ID: "e1", Author: "agent", Timestamp: t1}); err != nil {
		t.Fatalf("AppendEvent (fresh handle): %v", err)
	}
	// Appending through the stale handle (updatedAt == t0 < stored t1) must fail.
	err = s.AppendEvent(t.Context(), staleHandle, &session.Event{ID: "e2", Author: "agent", Timestamp: t1})
	if err == nil {
		t.Fatal("AppendEvent through stale handle: got nil error, want stale session error")
	}
	msg := err.Error()
	if !strings.Contains(msg, "stale session error") {
		t.Fatalf("error = %q, want a stale session error", msg)
	}
	if strings.Contains(msg, "1970") {
		t.Errorf("stale error still renders a 1970 timestamp (UnixMicro passed to time.Unix nsec arg): %q", msg)
	}
	// Mirror the exact formatting the code uses (UnixMicro -> local time ->
	// RFC3339Nano) so the assertion is timezone-independent. The request side
	// is the stale handle's t0; the database side is the advanced t1.
	wantRequest := time.UnixMicro(t0.UnixMicro()).Format(time.RFC3339Nano)
	wantDatabase := time.UnixMicro(t1.UnixMicro()).Format(time.RFC3339Nano)
	if !strings.Contains(msg, wantRequest) {
		t.Errorf("stale error missing request timestamp %q: %q", wantRequest, msg)
	}
	if !strings.Contains(msg, wantDatabase) {
		t.Errorf("stale error missing database timestamp %q: %q", wantDatabase, msg)
	}
}
