// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package session_test

import (
	"fmt"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"google.golang.org/adk/platform"
	"google.golang.org/adk/session"
	"google.golang.org/adk/session/sessiontestsuite"
)

func Test_inMemoryService_CreateUsesProviders(t *testing.T) {
	fixedTime := time.Date(2024, time.January, 2, 3, 4, 5, 0, time.UTC)
	ctx := platform.WithTimeProvider(t.Context(), func() time.Time { return fixedTime })
	ctx = platform.WithUUIDProvider(ctx, func() string { return "fixed-session-id" })

	s := session.InMemoryService()
	resp, err := s.Create(ctx, &session.CreateRequest{AppName: "app", UserID: "user"})
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	if got := resp.Session.ID(); got != "fixed-session-id" {
		t.Errorf("autogenerated session ID = %q, want provider value %q", got, "fixed-session-id")
	}
	if got := resp.Session.LastUpdateTime(); !got.Equal(fixedTime) {
		t.Errorf("LastUpdateTime() = %v, want provider value %v", got, fixedTime)
	}
}

func Test_inMemoryService(t *testing.T) {
	opts := sessiontestsuite.SuiteOptions{SupportsUserProvidedSessionID: true} // InMemory supports custom IDs
	sessiontestsuite.RunServiceTests(t, opts, func(t *testing.T) session.Service {
		return session.InMemoryService()
	})
}

func Test_inMemoryService_CreateConcurrentAccess(t *testing.T) {
	s := session.InMemoryService()
	const goroutines = 16
	const attempts = 32

	start := make(chan struct{})
	var wg sync.WaitGroup
	wg.Add(goroutines)

	req := &session.CreateRequest{
		AppName:   "race-app",
		UserID:    "race-user",
		SessionID: "race-session",
	}

	var successCount atomic.Int32
	var errorCount atomic.Int32

	for range goroutines {
		go func() {
			defer wg.Done()
			<-start
			for range attempts {
				_, err := s.Create(t.Context(), req)
				if err == nil {
					successCount.Add(1)
				} else if strings.Contains(err.Error(), "already exists") {
					errorCount.Add(1)
				}
			}
		}()
	}

	close(start)
	wg.Wait()

	if successCount.Load() != 1 {
		t.Errorf("expected 1 successful creation, but got %d", successCount.Load())
	}

	expectedErrors := int32(goroutines*attempts - 1)
	if errorCount.Load() != expectedErrors {
		t.Errorf("expected %d 'already exists' errors, but got %d", expectedErrors, errorCount.Load())
	}
}

func TestInMemorySession_AppendEvent_Deadlock(t *testing.T) {
	ctx := t.Context()
	service := session.InMemoryService()

	// Create a session
	createReq := &session.CreateRequest{
		AppName: "testapp",
		UserID:  "testuser",
	}
	createResp, err := service.Create(ctx, createReq)
	if err != nil {
		t.Fatalf("Failed to create session: %v", err)
	}
	sess := createResp.Session

	// Event with StateDelta to trigger updateSessionState
	event := &session.Event{
		ID:        "event1",
		Timestamp: time.Now(),
		Actions: session.EventActions{
			StateDelta: map[string]any{
				"test_key": "test_value",
			},
		},
	}

	// This call should hang if the deadlock is present
	err = service.AppendEvent(ctx, sess, event)
	if err != nil {
		t.Fatalf("AppendEvent failed: %v", err)
	}

	// If it doesn't hang, the test passes (meaning no deadlock)
	t.Log("AppendEvent did not deadlock")
}

func TestInMemoryService_AppendEvent_PreservesInputEventTempState(t *testing.T) {
	ctx := t.Context()
	service := session.InMemoryService()

	createResp, err := service.Create(ctx, &session.CreateRequest{
		AppName: "testapp",
		UserID:  "testuser",
	})
	if err != nil {
		t.Fatalf("Failed to create session: %v", err)
	}

	event := &session.Event{
		ID:        "event1",
		Timestamp: time.Now(),
		Actions: session.EventActions{
			StateDelta: map[string]any{
				"temp:k1": "v1",
				"sk":      "v2",
			},
		},
	}

	if err := service.AppendEvent(ctx, createResp.Session, event); err != nil {
		t.Fatalf("AppendEvent failed: %v", err)
	}

	// Verify that the input event pointer's StateDelta map was not mutated in place.
	if _, exists := event.Actions.StateDelta["temp:k1"]; !exists {
		t.Errorf("expected temp:k1 to be preserved on input event after AppendEvent, but it was removed: %v", event.Actions.StateDelta)
	}
	if event.Actions.StateDelta["sk"] != "v2" {
		t.Errorf("expected non-temp key sk to remain in input event, got: %v", event.Actions.StateDelta)
	}

	// Verify that the stored event in the session has temp keys stripped.
	var storedEvent *session.Event
	for ev := range createResp.Session.Events().All() {
		storedEvent = ev
	}
	if storedEvent == nil {
		t.Fatalf("expected stored event in session, got nil")
	}
	if _, exists := storedEvent.Actions.StateDelta["temp:k1"]; exists {
		t.Errorf("expected temp:k1 to be stripped from stored event, but it still exists: %v", storedEvent.Actions.StateDelta)
	}
	if storedEvent.Actions.StateDelta["sk"] != "v2" {
		t.Errorf("expected non-temp key sk on stored event, got: %v", storedEvent.Actions.StateDelta)
	}
}

// TestInMemoryService_AppendEvent_StripsTempKeysFromCanonicalRecord covers
// what TestInMemoryService_AppendEvent_PreservesInputEventTempState does not:
// Create() and AppendEvent() hand callers a session.Session distinct from the
// service's own canonical record, so re-reading temp: stripping through that
// same handle cannot catch a bug in how the canonical record is built. A fresh Get() call is
// required to observe what any other caller (e.g. a later turn, a different
// goroutine) actually sees.
func TestInMemoryService_AppendEvent_StripsTempKeysFromCanonicalRecord(t *testing.T) {
	ctx := t.Context()
	service := session.InMemoryService()

	createResp, err := service.Create(ctx, &session.CreateRequest{
		AppName: "testapp",
		UserID:  "testuser",
	})
	if err != nil {
		t.Fatalf("Failed to create session: %v", err)
	}

	event := &session.Event{
		ID:        "event1",
		Timestamp: time.Now(),
		Actions: session.EventActions{
			StateDelta: map[string]any{
				"temp:k1": "v1",
				"sk":      "v2",
			},
		},
	}
	if err := service.AppendEvent(ctx, createResp.Session, event); err != nil {
		t.Fatalf("AppendEvent failed: %v", err)
	}

	getResp, err := service.Get(ctx, &session.GetRequest{
		AppName:   "testapp",
		UserID:    "testuser",
		SessionID: createResp.Session.ID(),
	})
	if err != nil {
		t.Fatalf("Get failed: %v", err)
	}

	var storedEvent *session.Event
	for ev := range getResp.Session.Events().All() {
		storedEvent = ev
	}
	if storedEvent == nil {
		t.Fatalf("expected stored event in session, got nil")
	}
	if _, exists := storedEvent.Actions.StateDelta["temp:k1"]; exists {
		t.Errorf("temp:k1 leaked into the canonical record returned by Get(): %v", storedEvent.Actions.StateDelta)
	}
	if storedEvent.Actions.StateDelta["sk"] != "v2" {
		t.Errorf("expected non-temp key sk on stored event, got: %v", storedEvent.Actions.StateDelta)
	}
}

// TestInMemoryService_AppendEvent_MultipleEventsAllStripped guards against a
// narrower fix that only handles the first appended event: each event in a
// multi-turn session must independently have its temp: keys stripped from
// the canonical record.
func TestInMemoryService_AppendEvent_MultipleEventsAllStripped(t *testing.T) {
	ctx := t.Context()
	service := session.InMemoryService()

	createResp, err := service.Create(ctx, &session.CreateRequest{
		AppName: "testapp",
		UserID:  "testuser",
	})
	if err != nil {
		t.Fatalf("Failed to create session: %v", err)
	}

	for i, tempVal := range []string{"first", "second", "third"} {
		event := &session.Event{
			ID:        fmt.Sprintf("event%d", i),
			Timestamp: time.Now(),
			Actions: session.EventActions{
				StateDelta: map[string]any{
					"temp:turn": tempVal,
					"turn":      i,
				},
			},
		}
		if err := service.AppendEvent(ctx, createResp.Session, event); err != nil {
			t.Fatalf("AppendEvent(%d) failed: %v", i, err)
		}
	}

	getResp, err := service.Get(ctx, &session.GetRequest{
		AppName:   "testapp",
		UserID:    "testuser",
		SessionID: createResp.Session.ID(),
	})
	if err != nil {
		t.Fatalf("Get failed: %v", err)
	}

	i := 0
	for ev := range getResp.Session.Events().All() {
		if _, exists := ev.Actions.StateDelta["temp:turn"]; exists {
			t.Errorf("event %d: temp:turn leaked into the canonical record: %v", i, ev.Actions.StateDelta)
		}
		if ev.Actions.StateDelta["turn"] != i {
			t.Errorf("event %d: expected non-temp key turn=%d, got: %v", i, i, ev.Actions.StateDelta)
		}
		i++
	}
	if i != 3 {
		t.Fatalf("expected 3 stored events, got %d", i)
	}
}

// TestInMemoryService_AppendEvent_AllTempKeysStrippedKeepsEmptyDelta covers the
// one input class where stripping changes the shape of the stored delta rather
// than its contents: every key is temp:, so the map goes from populated to
// allocated-but-empty. It must not become nil — encoding/json writes a nil map
// as null and an empty one as {}, so the two serialize differently.
func TestInMemoryService_AppendEvent_AllTempKeysStrippedKeepsEmptyDelta(t *testing.T) {
	ctx := t.Context()
	service := session.InMemoryService()

	createResp, err := service.Create(ctx, &session.CreateRequest{
		AppName: "testapp",
		UserID:  "testuser",
	})
	if err != nil {
		t.Fatalf("Failed to create session: %v", err)
	}

	event := &session.Event{
		ID:        "event1",
		Timestamp: time.Now(),
		Actions: session.EventActions{
			StateDelta: map[string]any{"temp:a": 1},
		},
	}
	if err := service.AppendEvent(ctx, createResp.Session, event); err != nil {
		t.Fatalf("AppendEvent failed: %v", err)
	}

	getResp, err := service.Get(ctx, &session.GetRequest{
		AppName:   "testapp",
		UserID:    "testuser",
		SessionID: createResp.Session.ID(),
	})
	if err != nil {
		t.Fatalf("Get failed: %v", err)
	}

	stored := getResp.Session.Events().At(0)
	if stored == nil {
		t.Fatalf("expected stored event in session, got nil")
	}
	if stored.Actions.StateDelta == nil {
		t.Fatal("stored StateDelta is nil; stripping every key must leave an empty map, not nil")
	}
	if n := len(stored.Actions.StateDelta); n != 0 {
		t.Errorf("stored StateDelta = %v, want empty", stored.Actions.StateDelta)
	}
}

// TestInMemoryService_AppendEvent_CanonicalRecordDoesNotAliasLiveDelta pins
// that the canonical record's StateDelta is a map of its own, not the one the
// live session handle publishes.
//
// AppendEvent builds that field from the delta the session returns while
// holding only the service lock, never the session's own mutex. The map the
// session appends to its event list is reachable by anyone holding the handle
// the moment that mutex is released, so if the canonical record takes the map
// itself rather than a copy made under the lock, a caller walking session
// history writes into a map AppendEvent reads. A concurrent map read and write
// is a runtime throw rather than a recoverable panic.
//
// Sharing is what this can observe; the lock the copy is taken under is not.
// Proving that needs a concurrent writer, which reproduces only
// probabilistically and takes the test binary down with it when it fires.
func TestInMemoryService_AppendEvent_CanonicalRecordDoesNotAliasLiveDelta(t *testing.T) {
	// Both delta shapes matter. trimTempDeltaState returns the event unchanged
	// when it strips nothing, so with no temp: key the live session publishes
	// the caller's own map and the canonical record is one careless assignment
	// away from sharing it. With a temp: key the published map is a fresh one,
	// and it is that map the canonical record must not take.
	for _, tc := range []struct {
		name  string
		delta map[string]any
	}{
		{"temp key stripped", map[string]any{"temp:scratch": "x", "keep": "y"}},
		{"nothing stripped", map[string]any{"keep": "y"}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			ctx := t.Context()
			service := session.InMemoryService()

			createResp, err := service.Create(ctx, &session.CreateRequest{AppName: "app", UserID: "user"})
			if err != nil {
				t.Fatalf("Create: %v", err)
			}
			live := createResp.Session

			event := &session.Event{
				ID:        "e1",
				Timestamp: time.Now(),
				Actions:   session.EventActions{StateDelta: tc.delta},
			}
			if err := service.AppendEvent(ctx, live, event); err != nil {
				t.Fatalf("AppendEvent: %v", err)
			}

			// Write through the handle the caller still holds, the way a
			// goroutine reading session history would reach it.
			stored := live.Events().At(0)
			if stored == nil {
				t.Fatal("expected an event on the live session handle")
			}
			stored.Actions.StateDelta["injected"] = true
			// And through the caller's own event.
			event.Actions.StateDelta["also-injected"] = true

			got, err := service.Get(ctx, &session.GetRequest{
				AppName:   "app",
				UserID:    "user",
				SessionID: live.ID(),
			})
			if err != nil {
				t.Fatalf("Get: %v", err)
			}
			canonical := got.Session.Events().At(0).Actions.StateDelta
			if _, ok := canonical["injected"]; ok {
				t.Errorf("canonical StateDelta = %v: it shares the map the live handle publishes, "+
					"so a reader of session history can write into a map AppendEvent reads without the session lock", canonical)
			}
			if _, ok := canonical["also-injected"]; ok {
				t.Errorf("canonical StateDelta = %v: it shares the caller's map", canonical)
			}
			if canonical["keep"] != "y" {
				t.Errorf("canonical StateDelta = %v, want the non-temp key preserved", canonical)
			}
		})
	}
}
